### ISSUE TITLE
keynav doesn't work after restarting thunderbird

### ISSUE THREAD

**Issue by bin101** [hartag/keynav#1] opened 2020-09-15 10:06 UTC
I don't know with what version this issue started but under at least Thunderbird 68.12.0 this happens.

After restarting Thunderbird I have to disable and re-enable the whole plugin so that I get key navigation working again.

I am facing this issue under 3 different system ( 2 laptops (one which arch linux and one with manjaro) and 1 desktop PC with Windows 10)

**Comment by Landsdown** [comment] 2020-10-15 15:26
Thunderbird 78.3.2 Windows 8.1 on PC and laptop. Same problem as bin101

**Comment by bin101** [comment] 2020-10-16 23:27
I use the "Vertical View" layout. If I switch back to the default "Classic View" layout, the issue is gone after restarting.

**Comment by bin101** [comment] 2020-10-17 13:31
After some time of investigation I noticed that the current plugin version is now downwards compatible.
On Thunderbird 68 I was able to identify these points if I used the vertical layout:
1. onUpdated emits only once with status "loading" and never with completed (regardless if changeinfo.status or tab.status was checked)
2. during onUpdated execution tab.mailTab always returns false even if the current tab was the mail tab

Thunderbird 68 seems to use a really old chrome JS API lib or the implementation is very bad... I think I just wait for the newer Thunderbird versions to be stable and with good pgp support.

A workaround would be to remove all tab status and mailTab checks inside the background.js file.

**Comment by hartag** [comment] 2020-10-27 16:04
I took a look at the tab.mailTab problem and in TB 68.12.1 at least, some judicious console.debug printing allows me to see that tab.mailTab in the tabs.onUpdated event is capable of returning true. Perhaps something got fixed in 68.12.1. In any case, I am unable to reproduce the issue being reported here. I suspect that there's some kind of timing issue due to the asynchronous nature of TB or perhaps some difference between the Windows and Linux/Mac implementations of TB that's causing the issue to manifest. I have refactored the add-on a fair bit and I'm hoping that this will solve the problem. I've merged my dev branch to master and pushed it to the GitHub repo. I'd appreciate it if you guys would be able to test it out on your systems and let me know if what I've done makes any difference for you.

**Comment by bin101** [comment] 2020-11-01 20:31
Sorry for the late response but I was able to test your changes and it working fine now :) Thanks

**Comment by hartag** [comment] 2020-11-03 00:50
That's great. Thanks for letting me know. I forgot to mention that I am also using vertical view--I thought I was using the classic view but it turns out I've had it set to vertical for a while and didn't realise it. I pushed a final bit of cleanup to master and bumped the version to 3.1. I've also pushed a V3.1 tag. The add-on  is now available for download on ATN. I'm closing this issue for now.

**Closed by hartag** 2020-11-03 00:50 UTC
