### ISSUE TITLE
Typing does not work as expected on TB 102.2.1

### ISSUE THREAD

**Issue by bos4711** [hartag/keynav#5] opened 2022-09-07 07:01 UTC
I have four mail accounts. On the first one, I have a sub-folder (two nests down) named "Mouser". My third mail account is named "mantis@somedomain.com". If I select the first mail account and type "m" the selection immediately jumps down to the third mail account since it starts with "m", instead of actually jump to "mouser".

I'm not sure what the option "Enable mail-folder key navigation" option does, but when it's off nothing at all happens when typing in the folder pane.

![Untitled](https://user-images.githubusercontent.com/11036018/188810916-ea602e23-c479-4e11-a037-bc13f01eeb3c.png)

**Comment by hartag** [comment] 2024-06-15 22:28
I'm not able to reproduce this issue on Thunderbird 102.15.0. Given that the UI has been completely written in 115.0, I'm not going to go back and revisit this, so I'm closing the issue.

**Closed by hartag** 2024-06-15 22:28 UTC
